### ISSUE TITLE
cCc Ferhan Reis cCc Commit yap

### ISSUE THREAD

**Issue by hmert** [MustafaFerhan/MFBitmapUtils#1]
![sabri](https://f.cloud.github.com/assets/182906/1981086/a39ccc24-83cf-11e3-945a-5f4bb9ad42b3.jpeg)

**Comment by MustafaFerhan** [comment]
hayırdır Android bitmap ile ilgili bi işin mi var :)

**Comment by hmert** [comment]
kod yaz arkadaşım

**Comment by MustafaFerhan** [comment]
kardeşim; gtalk var, fb var, whatsapp var, telefon var, sms var.. burayı mı buldun bana sataşacak :)

not: tam üstüne bastın.

**Comment by hmert** [comment]
bekliyoruz reis cCc
